version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./resources/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

#  postgres:
#    image: postgres:12-alpine
#    ports:
#      - '5432:5432'
#    restart: always
#    volumes:
#      - ./resources/:/docker-entrypoint-initdb.d
#    environment:
#      - POSTGRES_DB=db
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=pass

  gate-simulator:
    build: ./gate-simulator
    image: gate-simulator
    ports:
      - '9999:9999'

